config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'

  devise_for :users,
             path: '',
             path_names: {sign_in:'login', sign_out: 'logout', edit: 'profile'},
             controllers: {omniauth_callbacks: 'omniauth_callbacks', registrations: 'registrations'}
  resources :users, only: [:show]
  resources :rooms
  resources :photos

  resources :rooms do
    resources :reservations, only: [:create]
  end

  resources :conversations, only: [:index, :create] do
    resources :messages, only: [:index, :create]
  end

  resources :rooms do
    resources :reviews, only: [:create, :destroy]
  end

  get '/preload' => 'reservations#preload'
  get '/preview' => 'reservations#preview'
  get '/your_trips' => 'reservations#your_trips'
  get '/your_reservations' => 'reservations#your_reservations'
  get '/search' => 'pages#search'
  get '/privacy_policy' => 'pages#privacy_policy'

  post '/notify' => 'reservations#notify'
  post '/your_trips' => 'reservations#your_trips'

end

app/models/room.rb
class Room < ApplicationRecord
  #TODO must validate the the room has a photo before generating the room.

  belongs_to :user
  has_many :photos
  has_many :reservations
  has_many :reviews

  geocoded_by :address
  after_validation :geocode, if: :address_changed?

  validates :home_type, presence: true
  validates :room_type, presence: true
  validates :accommodate, presence: true
  validates :bed_room, presence: true
  validates :bath_room, presence: true
  validates :listing_name, presence: true, length: {maximum: 50}
  validates :summary, presence: true, length: {maximum: 50}
  validates :address, presence: true
  validates :price, numericality: {only_integer: true, greater_than: 5}

  def show_first_photo(size = nil)
    if self.photos.length == 0
      #used conditional because default image for paperclip is buggy
      #TODO work on fixing paperclip default image bug-ness
      # it may make more sence to check if a model has a photo in the view and if not link to cloudinery default
      ActionController::Base.helpers.asset_path('default-burning-house.jpg')
    else
      self.photos[0].image.url(size)
    end
  end

  def average_rating
    reviews.count == 0 ? 0 : reviews.average(:star).round(2)
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: [:show, :edit, :update]
  before_action :authenticate_user!, except: [:show]

  def index
    @rooms = current_user.rooms
  end

  def show
    @photos = @room.photos

    @booked = Reservation.where("room_id = ? AND user_id = ?", @room.id, current_user.id).present? if current_user
    @reviews = @room.reviews
    @hasReview = @reviews.find_by(user_id: current_user.id) if current_user
  end

  def new
    @room = current_user.rooms.build
  end

  def create
    @room = current_user.rooms.build(room_params)

    if @room.save
      if params[:images]
        params[:images].each do |img|
          @room.photos.create(image: img)
        end
      end
      @photos = @room.photos
      redirect_to rooms_path, notice: "Saved..."
    else
      flash[:alert] = "Please provide all information for this room."
      render :new
    end
  end

  def edit
    if current_user.id == @room.user.id
      @photos = @room.photos
    else
      redirect_to root_path, notice: "You do not have permission."
    end
  end

  def update
    if @room.update(room_params)
      if params[:images]
        params[:images].each do |img|
          @room.photos.create(image: img)
        end
      end
      redirect_to rooms_path, notice: "Updated..."

    else
      flash[:alert] = "Please provide all information for this room."
      render :edit
    end
  end

  private
    def set_room
      def self.set_room
        @room
      end
      @room = Room.find(params[:id])
    end

    def room_params
      params.require(:room).permit(:home_type, :room_type, :accommodate, :bed_room, :bath_room, :listing_name, :summary, :address, :is_tv, :is_kitchen, :is_air, :is_heating, :is_internet, :price, :active, :image)
    end
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/_form.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    Detail your beautiful place
  </div>

  <div class="panel-body">
    <div class="container">

      <%= form_for @room, html: {multipart: true} do |f| %>

        <div class="row">
          <div class="col-md-4 select">
            <div class="form-group">
              <label>Home Type</label>
              <%= f.select :home_type, [["Appartment", "Appartment"], ["House", "House"], ["Bed & Breakfast", "Bed & Breakfast"]], prompt: "Select...", class: "form-control" %>
            </div>
          </div>

          <div class="col-md-4 select">
            <div class="form-group">
              <label>Room Type</label>
              <%= f.select :room_type, [["Entire", "Entire"], ["Private", "Private"], ["Shared", "Shared"]], prompt: "Select...", class: "form-control" %>
            </div>
          </div>

          <div class="col-md-4 select">
            <div class="form-group">
              <label>Accommodate</label>
              <%= f.select :accommodate, [["1", 1], ["2", 2],["3", 3],["4", 4],["5", 5],["6+", 6]], prompt: "Select...", class: "form-control" %>
            </div>
          </div>

        </div>
        <div class="row">

          <div class="col-md-4 select">
            <div class="form-group">
              <label>Bedrooms</label>
              <%= f.select :bed_room, [["1", 1], ["2", 2], ["3", 3], ["4+", 4]], prompt: "Select...", class: "form-control" %>
            </div>
          </div>

          <div class="col-md-4 select">
            <div class="form-group">
              <label>Bathrooms</label>
              <%= f.select :bath_room, [["1", 1], ["2", 2], ["3", 3], ["4+", 4]], prompt: "Select...", class: "form-control" %>
            </div>
          </div>

        </div>
        <div class="row">
          <div class="form-group">
            <label>Listing Name</label>
            <%= f.text_field :listing_name, placeholder: "Name you listing", class: "form-control" %>
          </div>
        </div>
        <div class="row">
          <div class="form-group">
            <label>Summary</label>
            <%= f.text_area :summary, rows: 5, placeholder: "Tell us about your house", class: "form-control" %>
          </div>
        </div>
        <div class="row">
          <div class="form-group">
            <label>Address</label>
            <%= f.text_field :address, placeholder: "What is the address", class: "form-control" %>
          </div>
        </div>
        <div class="row">

          <div class="col-md-4">
            <div class="form-group">
              <%= f.check_box :is_tv %> TV
            </div>
            <div class="form-group">
              <%= f.check_box :is_kitchen %> Kitchen
            </div>
            <div class="form-group">
              <%= f.check_box :is_internet %> Internet
            </div>
          </div>

          <div class="col-md-4">
            <div class="form-group">
              <%= f.check_box :is_heating %> Heat
            </div>
            <div class="form-group">
              <%= f.check_box :is_air %> A/C
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-md-4">
            <div class="form-group">
              <label>Nightly Price</label>
              <div class="input-group">
                <div class="input-group-addon">$</div>
                <%= f.text_field :price, placeholder: "eg. $100", class: "form-control" %>
              </div>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-md-4">
            <div class="form-group">
              <span class="btn btn-default btn-file">
                <i class="fa fa-cloud-upload fa-lg"></i> Upload photos
                <%= file_field_tag "images[]", type: :file, multiple: true %>
              </span>
            </div>
          </div>
        </div>
        <div id="photos">
          <%= render 'photos/list' %>
        </div>
        <div class="row">
          <div class="form-group">
            <%= f.check_box :active %> Active
          </div>
        </div>
        <div class="actions">
          <%= f.submit "Save", class: "btn btn-primary" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/rooms/create.html.erb
<h1>Rooms#create</h1>
<p>Find me in app/views/rooms/create.html.erb</p>

app/views/rooms/edit.html.erb
<%= render 'form' %>

app/views/rooms/index.html.erb
<div class="row">
  <div class="col-md-3">
    <ul class="sidebar-list">
      <li class="sidebar-item"><%= link_to "Your Listings", rooms_path, class: "sidebar-link active" %></li>
      <li class="sidebar-item"><%= link_to "Your Reservations", your_reservations_path, class: "sidebar-link" %></li>
      <li class="sidebar-item"><%= link_to "Your Trips", your_trips_path, class: "sidebar-link" %></li>
    </ul>
  </div>
  <div class="col-md-9">
    <div class="panel panel-default">
      <div class="panel-heading">
        Listings
      </div>
      <div class="panel-body">
        <% @rooms.each do |room| %>
          <div class="row">
            <div class="col-md-3">
              <!--TODO: has inline style due to default image conditional not using paperclip styles -->
             <%= image_tag room.show_first_photo(:thumb), style: "width:100px;height:80px;" %>
            </div>
            <div class="col-md-6">
              <h4><%= room.listing_name %></h4>
            </div>
            <div class="col-md-3 right">
              <%= link_to "Update", edit_room_path(room), class: "btn btn-primary" %>
            </div>
          </div>
          <hr>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/rooms/new.html.erb
<%= render 'form' %>

app/views/rooms/show.html.erb
<!--TODO Must make images responsive and fit to view. I am using bootstrap and
added class="image-responsive" i am also using paperclip...  -->

<div class="panel panel-default">
  <div class="panel-body">
    <!-- image -->
    <div class="row">
      <div class="col-md-12">
          <%= image_tag @room.show_first_photo(), style: "width:100%" %>
      </div>
    </div>
    <br>

    <!-- Main Info -->
    <div class="row">
      <div class="col-md-8">
        <div class="row">
          <div class="col-md-3 text-center">
            <%= image_tag avatar_url(@room.user), class: "img-circle avatar-large" %> <br><br>
            <%= @room.user.fullname%>
          </div>
          <div class="col-md-9">
            <h4><%= @room.listing_name %></h4>
            <%= @room.address %>
            <div class="row text-center row-space-1">
              <div class="col-sm-3">
                <i class="fa fa-home fa-2x"></i>
              </div>
              <div class="col-sm-3">
                <i class="fa fa-users fa-2x"></i>
              </div>
              <div class="col-sm-3">
                <i class="fa fa-bed fa-2x"></i>
              </div>
              <div class="col-sm-3">
                <i class="fa fa-ship fa-2x"></i>
              </div>
            </div>

            <div class="row text-center">
              <div class="col-sm-3">
                <%= @room.home_type%>
              </div>
              <div class="col-sm-3">
                <%= pluralize(@room.accommodate, "Guest")%>
              </div>
              <div class="col-sm-3">
                <%= pluralize(@room.bed_room, "Bedroom")%>
              </div>
              <div class="col-sm-3">
                <%= pluralize(@room.bath_room, "Bathroom")%>
              </div>
            </div>
          </div>
        </div>
      </div>

      <div class="col-md-4">
        <!-- reservation form -->
        <%= render 'reservations/form' %>
      </div>
    </div>
    <!-- about -->
    <div class="row">
      <div class="col-md-12">
        <h2>About this Listing</h2>
        <p><%= @room.summary %></p>
      </div>
    </div>
    <!-- amenitits -->
    <div class="row">
      <div class="col-md-2">
        <p>Amentities</p>
      </div>
      <div class="col-md-10">
        <div class="row">
          <div class="col-md-6">
            <ul class="amenities">
              <li class="<%= 'text-line-through' if !@room.is_tv %>">TV</li>
              <li class="<%= 'text-line-through' if !@room.is_kitchen %>">Kitchen</li>
              <li class="<%= 'text-line-through' if !@room.is_internet %>">Internet</li>
            </ul>
          </div>
          <div class="col-md-6">
            <ul class="amenities">
              <li class="<%= 'text-line-through' if !@room.is_heating %>">Heating</li>
              <li class="<%= 'text-line-through' if !@room.is_air %>">Air Conditioning</li>
            </ul>
          </div>
        </div>
      </div>
    </div>

    <% if @photos.count > 0 %>
    <!-- carousel -->
    <div class="row">
      <div class="col-md-10 col-md-offset-1">


        <div id="myCarousel" class="carousel slide" data-ride="carousel">
          <!-- Indicators -->

            <ol class="carousel-indicators">
              <% @photos.each do |photo| %>
                <li data-target="#myCarousel" data-slide-to="<%= photo.id %>"></li>
              <% end %>
            </ol>

          <!-- Wrapper for slides -->

          <div class="carousel-inner" role="listbox">
            <% @photos.each do |photo| %>
              <div class="item <%= 'active' if photo.id == @photos[0].id %>">
                <%= image_tag photo.image.url(), class: "image-responsive" %>
              </div>
            <% end %>
          </div>


          <!-- Left and right controls -->
          <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
            <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
          </a>
          <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
            <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
          </a>
        </div>

      </div>
    </div>
    <br>
    <%end%>
    <hr>

    <!--  reviews -->
    <div class="row">
      <div class="col-md-12">
        <h3>Reviews <span id="average_rating"></span> (<%= @reviews.count %>)</h3>
        <div class="container">
          <div>
            <%= render 'reviews/form' if @booked && !@hasReview %>
          </div>
          <div>
            <%= render 'reviews/list' %>
          </div>

        </div>
      </div>
    </div>
    <!-- google map -->
    <div class="row">
      <div class="col-md-12">
      <style>
        #map {
          height: 400px;
          width: 100%;
        }
      </style>
        <div id="map"></div>
        <script>
          function initMap() {
            var uluru = {lat: <%= @room.latitude%>, lng: <%= @room.longitude %>};
            var map = new google.maps.Map( document.getElementById('map'), { zoom: 9, center: uluru} );
            var marker = new google.maps.Marker({position: uluru, map: map});
          }
        </script>
        <script async defer
            src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBIg_DGlq_GlACo69mlq4CIV-iB7dNLIvE&callback=initMap">
        </script>
      </div>
    </div>
    <!-- Near by rooms -->
    <h3>Near By</h3>
    <div class="row">
      <% for room in @room.nearbys(10) %>
        <div class="col-md-4">
          <div class="panel panel-default">
            <div class="panel-heading preview">
              <%= image_tag room.show_first_photo(:medium) %>
            </div>
            <div class="panel-body">
              <%= link_to room.listing_name, room %><br>
              (<%= room.distance.round(2) %> miles away)
            </div>
          </div>
        </div>
      <% end %>
    </div>

  </div>
</div>

<script>
  $('#average_rating').raty({
    path: '/assets',
    readOnly: true,
    score: <%= @room.average_rating %>
  });
</script>

app/views/rooms/update.html.erb
<h1>Rooms#update</h1>
<p>Find me in app/views/rooms/update.html.erb</p>